create extension if not exists "pgcrypto";

create table if not exists profiles (
  user_id uuid primary key default gen_random_uuid(),
  username text not null unique,
  bio text,
  profile_pic_url text,
  created_at timestamptz not null default now()
);

create table if not exists categories (
  id int generated by default as identity primary key,
  name text not null,
  parent_id int references categories(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists reviews (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  excerpt text not null,
  content_html text,
  rating_avg numeric,
  rating_count int default 0,
  votes_up int default 0,
  votes_down int default 0,
  photo_urls jsonb,
  photo_count int default 0,
  category_id int not null references categories(id) on delete restrict,
  sub_category_id int references categories(id) on delete set null,
  user_id uuid not null references profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  source text,
  source_url text unique
);

create table if not exists comments (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null references reviews(id) on delete cascade,
  user_id uuid not null references profiles(user_id) on delete cascade,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists review_votes (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null references reviews(id) on delete cascade,
  user_id uuid references profiles(user_id) on delete set null,
  ip_hash text,
  type text not null,
  created_at timestamptz not null default now(),
  constraint review_votes_user_or_ip_check check (
    user_id is not null or ip_hash is not null
  ),
  constraint review_votes_unique_user unique (review_id, user_id),
  constraint review_votes_unique_ip unique (review_id, ip_hash)
);

create index if not exists idx_reviews_category_created_at
  on reviews (category_id, created_at desc);

create index if not exists idx_reviews_category_votes_up
  on reviews (category_id, votes_up desc);

create index if not exists idx_reviews_slug on reviews (slug);

create index if not exists idx_comments_review_created_at
  on comments (review_id, created_at desc);
